pipeline{
    agent any
    tools {
    maven 'maven3'
    }
    stages{
        stage('SCM'){
            steps{
                git credentialsId: 'github',
                url: 'https://github.com/shvkmr536/application_repo.git'
                    
            }
        }
        
        stage('Maven Build'){
            steps{
                sh "mvn clean package"
            }
        }
          stage('Deployment'){
            steps{
                sshagent(['ansible']) {
                sh 'ssh vagrant@192.168.0.102 "./tomcat.sh"'
                 }
            }
        }
     
    }
}
